version: 0.2

env:
  variables:
    COVERAGE_MIN: "70"  # luego lo subimos a 95 para forzar un rojo de evidencia

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "[INSTALL] Actualizando pip/setuptools/wheel"
      - pip install --upgrade pip setuptools wheel
      - echo "[INSTALL] Dependencias de la app"
      - pip install -r blacklist-ms/requirements.txt
      - echo "[INSTALL] Dependencias de test"
      - |
        if [ -f "requirements-dev.txt" ]; then
          pip install -r requirements-dev.txt
        else
          pip install pytest pytest-cov requests
        fi

  pre_build:
    commands:
      - echo "[PRE_BUILD] Exportando PYTHONPATH y preparando BD SQLite"
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/blacklist-ms
      - export DATABASE_URL=sqlite:///ci.sqlite3
      - |
        python - <<'PY'
        import os
        from application import application as app
        from src.models import db
        # Garantizamos que la app use la misma URI definida en el entorno
        app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv("DATABASE_URL", "sqlite:///ci.sqlite3")
        with app.app_context():
            db.create_all()
        print("DB bootstrap OK con", app.config["SQLALCHEMY_DATABASE_URI"])
        PY

  build:
    commands:
      - echo "[BUILD] Ejecutando pruebas con cobertura mínima ${COVERAGE_MIN}%"
      - |
        set -e
        # Usar SIEMPRE la misma BD que en el bootstrap
        export DATABASE_URL=sqlite:///ci.sqlite3

        # Detectar dónde están las rutas reales
        COV_DIR="src"
        [ -d "blacklist-ms/src" ] && COV_DIR="blacklist-ms/src"

        COV_APP="application.py"
        [ -f "blacklist-ms/application.py" ] && COV_APP="blacklist-ms/application.py"

        TEST_DIR="tests"
        [ -d "blacklist-ms/tests" ] && TEST_DIR="blacklist-ms/tests"

        echo "Usando cobertura en: $COV_DIR y $COV_APP; tests en: $TEST_DIR"
        echo "DATABASE_URL=${DATABASE_URL}"

        pytest "$TEST_DIR" -vv --maxfail=1 --disable-warnings \
          --cov="$COV_DIR" \
          --cov="$COV_APP" \
          --cov-report=term-missing \
          --cov-fail-under="${COVERAGE_MIN}"

artifacts:
  files:
    - artifact/*.zip
  discard-paths: yes