version: 0.2

env:
  variables:
    COVERAGE_MIN: "98"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "[INSTALL] Actualizando pip/setuptools/wheel"
      - pip install --upgrade pip setuptools wheel
      - echo "[INSTALL] Dependencias de la app"
      - pip install -r blacklist-ms/requirements.txt
      - echo "[INSTALL] Dependencias de test"
      - |
        if [ -f "requirements-dev.txt" ]; then
          pip install -r requirements-dev.txt
        else
          pip install pytest pytest-cov requests
        fi

  pre_build:
    commands:
      - echo "[PRE_BUILD] Exportando PYTHONPATH y preparando BD SQLite"
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/blacklist-ms
      - export DATABASE_URL=sqlite:///ci.sqlite3
      - |
        python - <<'PY'
        import os
        from application import application as app
        import src.models as models
        from src.models import db
        from sqlalchemy import inspect

        app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv("DATABASE_URL", "sqlite:///ci.sqlite3")
        with app.app_context():
            db.create_all()
            print("DB bootstrap OK con", app.config["SQLALCHEMY_DATABASE_URI"])
            print("Tablas creadas (bootstrap):", inspect(db.engine).get_table_names())
        PY

  build:
    commands:
      - echo "[BUILD] Ejecutando pruebas con cobertura mínima ${COVERAGE_MIN}%"
      - |
        set -e
        export DATABASE_URL=sqlite:///ci.sqlite3
        export PYTHONPATH=$PYTHONPATH:$(pwd)/blacklist-ms

        python - <<'PY'
        import os
        from application import application as app
        from sqlalchemy import inspect
        from src.models import db
        app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv("DATABASE_URL", "sqlite:///ci.sqlite3")
        with app.app_context():
            print("DB previa a pytest:", app.config["SQLALCHEMY_DATABASE_URI"])
            print("Tablas existentes (pre-pytest):", inspect(db.engine).get_table_names())
        PY

        COV_DIR="src"
        [ -d "blacklist-ms/src" ] && COV_DIR="blacklist-ms/src"

        COV_APP="application.py"
        [ -f "blacklist-ms/application.py" ] && COV_APP="blacklist-ms/application.py"

        TEST_DIR="tests"
        [ -d "blacklist-ms/tests" ] && TEST_DIR="blacklist-ms/tests"

        echo "Usando cobertura en: $COV_DIR y $COV_APP; tests en: $TEST_DIR"
        echo "DATABASE_URL=${DATABASE_URL}"

        pytest "$TEST_DIR" -vv --maxfail=1 --disable-warnings \
          --cov="$COV_DIR" \
          --cov="$COV_APP" \
          --cov-report=term-missing \
          --cov-fail-under="${COVERAGE_MIN}"

  post_build:
    commands:
      - echo "[POST_BUILD] Empaquetando artefacto para CodePipeline"
      - rm -rf artifact && mkdir -p artifact
      - |
        python - <<'PY'
        import os, zipfile
        items = ['blacklist-ms', 'tests', 'pytest.ini']
        os.makedirs('artifact', exist_ok=True)
        with zipfile.ZipFile('artifact/build.zip', 'w', zipfile.ZIP_DEFLATED) as z:
            for item in items:
                if os.path.isdir(item):
                    for root, _, files in os.walk(item):
                        for f in files:
                            p = os.path.join(root, f)
                            z.write(p, p)
                elif os.path.exists(item):
                    z.write(item, item)
        print("ZIP creado en artifact/build.zip")
        PY
      - ls -la artifact

artifacts:
  files:
    - artifact/*.zip
  discard-paths: yes